version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=moretech5
      - POSTGRES_PASSWORD=moretech
      - POSTGRES_DB=moretech
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  backend:
    container_name: backend
    image: backend
    ports:
      - "5000:5000"
    expose:
      - 5000
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: on-failure
    depends_on:
      - postgres